name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x] # Specify the Node.js versions you want to test against
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2 # Updated to v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - name: Build Frontend
      run: |
        cd frontend
        npm i
        npm run build
